AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonLexRunBots
      Environment:
        Variables:
          TABLE_NAME: ChatbotInteractions
  InteractionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ChatbotInteractions
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST